### ISSUE TITLE
Order card improvements: Tabs and Simplification

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#108]
When an option is selected, it brings up all the possible orders for opening/closing long/short positions as well as providing liquidity. We should use tabs to separate these oroder types into long/short/liquidity to simplify the card.

The actual order card should have very minimal information and inputs. Underneath the review transaction button, there could be a dropdown to display the advanced info like price impact/gas fees. 

There should also be more information about what approvals/ tokens are needed to do certain transactions.

**Comment by Alexangelj** [comment]
Also need token balances to be labed as "your balance" or something like that.

**Comment by zachdt** [comment]
Should we display underlying asset balances anywhere (in the positions card or the order card or both)?

**Comment by Alexangelj** [comment]
I'm not sure what the best place to put this is, maybe the market header?

**Comment by zachdt** [comment]
Either the header or on the positions card, not sure there is an obvious choice.

**Comment by Alexangelj** [comment]
Fixed order card component in submit refactor
