### ISSUE TITLE
Add a + icon to option table rows

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#109]
It's not completely intuitive that clicking on the row will open an order interface. Let's add a + icon. The rows will still be clickable, but they will instead open the greeks data, while the + icon will add to the order.

**Comment by zachdt** [comment]
There are three main improvements needed for the options table.  The first is described above, currently clicking on a table row edits the order state to open the order card.  We need to add an add button (using material-ui icons) to the end of the row that performs this state change, clicking the row outside of this iconbutton should only open the greek panel.  

The second improvement we need is proper reserve/price styling.  Right now, the raw text populates the table cells.  A clever way to display reserve/pricing data is welcome.

The final improvement I want to see is that only one greek panel should be able to be opened at a time.  At the moment, you can open all the greek panels at once and it looks a bit messy.  As a bonus, you could use the useClickAway hook (`@/hook/utils/useClickAway`) to close these panels upon click away, but this is not a necessary feature at the moment.
