### ISSUE TITLE
Some text will be in front of the top bar

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#113]
Some of the text and images, like the option table headers and greek headers will go in front of the top bar when they are scrolled up. 

![image](https://user-images.githubusercontent.com/38409137/98877190-c19b1e80-2434-11eb-9cb6-f9db056f935e.png)

**Comment by zachdt** [comment]
z-index issue, however #104 conflicts with this issue I will have to wait
