### ISSUE TITLE
Label for markets with zero liquidity

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#117]
It's not the best user experience for users to visit a market that has no option liquidity. This will be the case for some markets/options, so we should have a label that looks like a banner displaying `This market has no liquidity: Add Liquidity Button`.

Also, if an option is chosen for an order, there should also be the same label in the order card with an easy way to provide liquidity.

**Comment by zachdt** [comment]
This will be a Warning notif that explains the steps to bootstrap liquidity.
