### ISSUE TITLE
Slug for specific options

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#118]
When an option is clicked on in from the options table row, it opens the order card. It should also redirect to the option's address in the url: `markets/weth/0xoptionaddress`. This should also make it very easily sharable with others. Sending this url to someone else should allow them to buy the options in one click (after they connect and approve).

But, we have different order types. For example, long/short buy/sell provide/withdraw. There should be an additional slug for the order type, maybe something like: `markets/weth/0xoptionaddress/orderType`

**Comment by zachdt** [comment]
Making `/markets/weth/ADDRESS` link to an empty orderType then '`/markets/weth/ADDRESS/orderType` links to a specific orderType

**Comment by zachdt** [comment]
This is actually going to be a proper query slug, much easier that way.  '/markets/weth/ADDRESS?orderType=TYPE'
