### ISSUE TITLE
Need fallback for market view if no wallet is connected

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#125]
Without a wallet connected, when options are being fetched it will throw this error:

![image](https://user-images.githubusercontent.com/38409137/99151038-3ba5f000-264d-11eb-8f36-fc4c30b94b83.png)

We should have a fallback provider to fetch web3 data from.

**Comment by Alexangelj** [comment]
Maybe we build a hook like useFallbackProvider() that would default to ethers mainnet provider.

**Comment by zachdt** [comment]
Adding to this issue -> metamask events listener for new network page refreshes

**Comment by Alexangelj** [comment]
![image](https://user-images.githubusercontent.com/38409137/99420302-eb7b9780-28b1-11eb-935a-8e2fd51d8564.png)

Still shows me the error when I am not connected
