### ISSUE TITLE
Greek details tabs should persist

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#133]
If a greek tab is opened from one of the option table rows, clicking on another row will close that greek tab and open the greek tab for the row that was clicked. It should just open a second greek details tab, instead of closing the one that is opened.

**Comment by Alexangelj** [comment]
This could be a feature though, I am assuming useClickAway is the root cause of this? Might as well keep as is.

**Comment by zachdt** [comment]
I think going to the robinhood path of allowing users to open all the options is fine, but i do think the UI feels cleaner with locking users into one at a time.  This is a feature but I have gone back and forth in my head about whether the cleanliness is worth the reduction in functionality.
