### ISSUE TITLE
Some reserves/premiums are not being displayed even though they exist

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#147]
![image](https://user-images.githubusercontent.com/38409137/99193104-9dd52280-272b-11eb-8882-372da424598c.png)

These markets have depth, which implies they have reserves, but its displaying reserves as 0. Same as price, since they have reserves, they have a price.

**Comment by zachdt** [comment]
I am viewing more reserves than normal on my latest branch, need a confirmation that this issue is still open.

**Comment by zachdt** [comment]
@Alexangelj can this issue be closed?  Kind of a critical bug
