### ISSUE TITLE
Kill the spacing between the tabs in order card?

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#155]
![image](https://user-images.githubusercontent.com/38409137/99292411-07216800-27f6-11eb-9241-0e69b699841e.png)

I think we kill the spacing, what do you think @zachdt ?

**Comment by zachdt** [comment]
I can try it out, i think the reason im using spacing here is to manually force the tabs to the edge of the div but i can figure out how to kill the spacing.
