### ISSUE TITLE
Underlying token balance is nowhere to be found...

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#156]
I got some feedback earlier, they thought the balance in the order card was their underlying token balance:
![image](https://user-images.githubusercontent.com/38409137/99292548-346e1600-27f6-11eb-8134-5b0175107ee8.png)

We should put the underlying token balance in a more global area, maybe the market header? its own card above positions/ordercard?

**Comment by zachdt** [comment]
Maybe we merge the get test tokens card and add the underlying balance there, then on testnet we add the button to get more underlying.  That makes the most sense to me

**Comment by zachdt** [comment]
This kind of interferes with a redesign idea ive had over the past few days but not by too much (permanent sidebar for all positions, market search on main).  Ill add the balances in the way described above.
