### ISSUE TITLE
Our PriceInput component should have input formatting/validation built in?

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#160]
The `PriceInput` component is an input with a combined label:
![image](https://user-images.githubusercontent.com/38409137/99293262-43a19380-27f7-11eb-8b9b-db0878941c60.png)

@nourharidy Had the idea of formatting/validating data input in that component. We could format it to a string and use strings mostly. Then for math, we could use `parseEther` to convert it to a bignumber.

**Comment by Alexangelj** [comment]
![image](https://user-images.githubusercontent.com/38409137/99296305-646be800-27fb-11eb-8f0d-72cc81ce4a75.png)

I also feel like the padding/margin on the left and right of inside the price input is a little too much?

Also, maybe the balance of the token you are inputting should be underneath and to the right of the input?

**Comment by zachdt** [comment]
Validation has been fixed in the BigInt refactor, closing this for now.
