### ISSUE TITLE
Formatting 0 values

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#161]
The depth column needs to format 0s as '-'.
![image](https://user-images.githubusercontent.com/38409137/99295926-db54b100-27fa-11eb-9134-e585573bb1e5.png)

Maybe we just include this in the formatting function, rather than having a conditional statement in the component? For example, the `formatBalance()` utility function will format 0s as hyphens.

**Comment by zachdt** [comment]
Done

**Comment by zachdt** [comment]
I do think it should be included in formatting function in the future, but for time purposes I am just going to edit the condition the table.
