### ISSUE TITLE
URL should also include if we are looking at puts or calls

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#162]
![image](https://user-images.githubusercontent.com/38409137/99305262-64beb000-2808-11eb-991e-e9649d207c90.png)

We are in SNX market, looking at calls, the url should reflect this!

**Comment by zachdt** [comment]
When you follow a slugged link for a put, the option isnt selected in the table.  Adding this feature will fix that inconsistency.
