### ISSUE TITLE
Strike prices less than $1.00 act weird

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#179]
![image](https://user-images.githubusercontent.com/38409137/99420589-3dbcb880-28b2-11eb-9d9b-07f17c306e6e.png)

The sushi $0.00 strike price is not 0.00, its 0.75, but its displayed as 0.00.

**Comment by zachdt** [comment]
Strike prices are being rounded in the option hook.  Fixing now...
