### ISSUE TITLE
Short token math inaccurate

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#182]
![image](https://user-images.githubusercontent.com/38409137/99437144-ed038a80-28c6-11eb-9c89-dec87c23f8e8.png)

I can work on this, the premiums should be the swap output.

**Comment by zachdt** [comment]
Noticed this as well.  When u start work assign yourself.

**Comment by Alexangelj** [comment]
![image](https://user-images.githubusercontent.com/38409137/99471359-3a99ea80-28fb-11eb-830f-e228ec5c880e.png)

More related issues, Required Comp isnt calculating.

Also, should add an Implied Price
