### ISSUE TITLE
Units on Balance when selling Long tokens is the underlying, should be Long Options

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#200]
![image](https://user-images.githubusercontent.com/38409137/99487670-bd32a200-291b-11eb-8d3d-ca425362e248.png)

**Comment by Alexangelj** [comment]
![image](https://user-images.githubusercontent.com/38409137/99487722-d63b5300-291b-11eb-8439-cce5d2b2440e.png)

Same thing for selling shorts

**Comment by Alexangelj** [comment]
![image](https://user-images.githubusercontent.com/38409137/99490243-506cd700-291e-11eb-8afc-dedfaf3fec9c.png)

Duplicate info here, maybe we take it out of order card

**Comment by zachdt** [comment]
Going to remove the balance card when order item is active.  Makes the balance more useful + cleans up the UI.
