### ISSUE TITLE
Puts are not handled correctly!

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#203]
![image](https://user-images.githubusercontent.com/38409137/99491253-4350e780-2920-11eb-9993-2174399a49de.png)

Underlying asset for puts is DAI not the underlying for the market

**Comment by Alexangelj** [comment]
![image](https://user-images.githubusercontent.com/38409137/99494715-5b2b6a00-2926-11eb-9763-940ce84fbc07.png)

Its simple issue, the item.asset is being passed as the symbol, but thats not the case for the puts, its just DAI

**Comment by zachdt** [comment]
Puts in need more testing, but this particular issue has been solved in #225
