### ISSUE TITLE
Add guardrails to UI to limit transaction sizes

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#205]
There should be soft guard rails around each transaction type to limit the inflow of funds. After caps are reached, and no issues come up, we can explore bumping up the caps.

Proposed caps:
- Purchase options $10,000 limit
- Purchase short options $10,000 limit
- Provide liquidity $15,000 limit
- Withdraws unlimited, sells unlimited.

Assuming the caps are hit for providing liquidity on all option series, there would be a little less than $1M locked in the contracts.

**Comment by zachdt** [comment]
The liquidity limit makes sense and should be fairly easy to implement.  Purchase limits are a bit of a pain, how do we determine the short/long limit when short minting is baked into providing liquidity?

**Comment by Alexangelj** [comment]
I think we can put caps on each of the order types, so purchasing long option tokens, premium is like .10 eth, cap is $10,000, eth is $500, so we can spend up to 20 eth, which is 200 long options max. 

For buying short tokens its same thing, because we are doing a normal uniswap swap from underlying -> short tokens.

**Comment by zachdt** [comment]
Ok the long/short order cap is determined at the point of purchase, and the liquidity cap is based on current reserves.  Makes sense.
