### ISSUE TITLE
Add 'contracts' page that will list all of Primitive's live contracts and a link to their audits

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#206]
Add a page that has a list of all Primitive protocol contracts. The list should have a column for "audits". If a contract is audited, provide a link to the audit. If contract is not audited, put a warning label with "not audited".

**Comment by zachdt** [comment]
No description right?  Just a list of addresses with a title, link to contract, maybe a visualization of the protocol hierarchy, and the warning tag/ audit tag.

**Comment by zachdt** [comment]
@Alexangelj could you write a CONTRACTS constant with the key [chainId] with the appropriate info you want in this page?  Addresses, names, date deployed, audit link.  This would save me a bit of time while I work on other issues.

**Comment by Alexangelj** [comment]
@zachdt I can do that!
