### ISSUE TITLE
100% LP Withdraw Fails

### ISSUE THREAD

**Issue by zachdt** [primitivefinance/primitive-interface#208]
RPC Error: "execution reverted: ds-math-sub-underflow" 

May need to add a small buffer to LP balance to prevent this error.

**Comment by Alexangelj** [comment]
I think it gets rounded up or something? I noticed this as well, will investigate later.

**Comment by Alexangelj** [comment]
Approving withdrawals doesnt seem to trigger enabling the submit button after approves were confirmed.

![image](https://user-images.githubusercontent.com/38409137/99693580-62df3180-2a40-11eb-9866-d06c0d5b46a2.png)

**Comment by Alexangelj** [comment]
Amount withdrawn in args:
![image](https://user-images.githubusercontent.com/38409137/99697876-fd417400-2a44-11eb-9fd9-5656da477779.png)

Actual balance
![image](https://user-images.githubusercontent.com/38409137/99697894-016d9180-2a45-11eb-8eee-0638595b7377.png)


Looks like its rounding up!

**Comment by Alexangelj** [comment]
Actual balance
![image](https://user-images.githubusercontent.com/38409137/99698793-0d0d8800-2a46-11eb-93ad-1a583fcb3ef4.png)

**Comment by Alexangelj** [comment]
This is not the issue! Removing liquidity also pulls long option tokens, so they can be closed and redeemed for underlying tokens. I don't have enough long option tokens to do this tx.

**Comment by Alexangelj** [comment]
99.9% withdraw works

**Comment by zachdt** [comment]
The approvals stuff is unrelated I believe, I'm still fixing a bug with the withdraw approvals.

**Comment by Alexangelj** [comment]
It is unrelated

**Comment by Alexangelj** [comment]
Found the issue! If the user does not have enough long tokens to withdraw all their liquidity, it will fail.

I added a line to show the required option balance:
![image](https://user-images.githubusercontent.com/38409137/99732529-80c68980-2a74-11eb-9268-476e7338f207.png)
