### ISSUE TITLE
Add dollar value to implied option premium in order card

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#211]
![image](https://user-images.githubusercontent.com/38409137/99696064-206b2400-2a43-11eb-842e-e1f54e0ade8f.png)
![image](https://user-images.githubusercontent.com/38409137/99696093-28c35f00-2a43-11eb-9617-74f815630bbf.png)

**Comment by Alexangelj** [comment]
This is not as straightforward. The <Swap> component would need to have the price data from coingecko. We could have a promise to grab it, but its not too efficient that way since we already grab that data in market header. What should we do here? @zachdt

**Comment by zachdt** [comment]
Price state with updater in the _app, like transactions.  Thinking of starting to use a market-agnostic approach to these state reducers, so the price state would grab all prices from all markets then we can choose which ones to use where, have a hook that can pull the current market price data, or all of them.

**Comment by zachdt** [comment]
This will take me like 5 minutes to do but im in the middle of working on another feature.  I can handle this.
