### ISSUE TITLE
Add liquidity order: clicking advanced on markets that aren't initialized triggers invariant failure

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#234]
This will get triggered
![image](https://user-images.githubusercontent.com/38409137/100133031-1b3f1800-2e3b-11eb-8a66-b49727aac614.png)

when the "advanced" tab is clicked
![image](https://user-images.githubusercontent.com/38409137/100133148-3e69c780-2e3b-11eb-9547-15ff1cb77469.png)

**Comment by Alexangelj** [comment]
Also, this market doesn't have liquidity, but its showing the add liquidity state for markets with liquidity, could be part of a larger issue.

**Comment by zachdt** [comment]
Similar to #196.  I am familiar with the no Liquidity / add Liquidity bug, closing this in the next PR
