### ISSUE TITLE
Total liquidity in market header is incorrectly calculated because of puts

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#255]
![image](https://user-images.githubusercontent.com/38409137/100285810-641fcb00-2f26-11eb-8840-c289b2ce81d1.png)

The puts have underlying tokens in dai, which shouldnt get counted in the total liquidity of the market! Maybe total liquidity should be ASSET / DAI ?

**Comment by zachdt** [comment]
so call and put liquidity?  I'll include this in today's PR
