### ISSUE TITLE
Related to issue #212. Underlyings input changes need to be propagated to the uniswap math file

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#284]
The inputs were changed for the add liquidity pile on function so that users could choose how many underlying tokens theyd like to deposit. This was updated in the component, but not the actual math that is used to execute the function.

**Comment by zachdt** [comment]
Using the swap/liquidity state, the math can be re-calculated on input.  Once  #285 is merged ill move the component math to the necessary state.
