### ISSUE TITLE
2% depth increases as options are bought

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#286]
![image](https://user-images.githubusercontent.com/38409137/101229526-7e0f8b00-3655-11eb-848c-b4d6bcdb7e15.png)

The option depth was about 7000 long, I purchased 100k options, and now the option depth is 9000. Weird how its going up!

**Comment by zachdt** [comment]
Is this issue still open?

**Comment by Alexangelj** [comment]
yes, depth needs a math equation i gotta figure out, working on that

**Comment by zachdt** [comment]
Closing with #330
