### ISSUE TITLE
1 DAI Strikes are ignored after fix

### ISSUE THREAD

**Issue by zachdt** [primitivefinance/primitive-interface#289]
After the fix to 1DAI strikes, they no longer are sorted by the options state hook

**Comment by Alexangelj** [comment]
If the base and quote value are both one, the next check for `isCall` and `isPut` is to compare the quote token symbol with Dai, if the quote token is DAI, then its a call. However, the testnet dai contract has the symbol and name set opposite, so the equality check is always failing. Issue with testnet. Goes to show we need checks for mainnet addresses.
