### ISSUE TITLE
Infinite loading symbol when purchasing options with no liquidity

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#308]
![image](https://user-images.githubusercontent.com/38409137/101652426-1362a480-39f3-11eb-9fb9-906b4560db26.png)

Never stops loading

**Comment by zachdt** [comment]
I have noticed this one time before, introducing the new callback loading system will prevent this, in the meantime if I replicate this bug again I will handle it beforehand.

**Comment by zachdt** [comment]
I will attempt to replicate this bug again, haven't seen it in a while.  All loading flags seem to be an artifact of positions or options state throwing a loading flag, which may be an intended feature in this case.

**Comment by zachdt** [comment]
If anyone can replicate this bug, let me know in this issue.  Cheers

**Comment by zachdt** [comment]
Finally replicated
