### ISSUE TITLE
Ordercard style changes, improve info density

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#309]
![proposed advanced menu](https://user-images.githubusercontent.com/38409137/101653160-e662c180-39f3-11eb-9ed0-909c2bf5bfde.png)

We should just have a text button that will open up the advanced menu to manage the options. The only necessary orders for many users are buying/selling long and providing liquidity. Everything else gets the axe.

I think the previous order card/balance card with the grey background was better
![image](https://user-images.githubusercontent.com/38409137/101653394-232eb880-39f4-11eb-8d1f-d168c9b69645.png)

The grey bg makes them more distinct cards, I think we can still go for the 'hover' effect, but it needs to be a lighter color grey (even more so than the market header).

The scrollbar on the side with the marketheader bg color is also a little weird:
![image](https://user-images.githubusercontent.com/38409137/101653622-5d985580-39f4-11eb-98d6-0c7db73ea76e.png)

Obviously not mission critical, but I thought I'd put down my thoughts on this.

**Comment by Alexangelj** [comment]
To add, I think the order card might look better as grey if the entire background is black (incl. market header), but I remember I was saying I liked the market header that color

**Comment by zachdt** [comment]
Robinhood pulls off the black background with grey order card for that exact reason.  I do think the market page needs to contrast with the sidebar in some way.  Ill experiment with a black market header version.
