### ISSUE TITLE
issue with bad gateway

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#314]
![image](https://user-images.githubusercontent.com/38409137/101826726-420c7800-3ae4-11eb-8ddd-7bb925e32cc4.png)

never seen this before

**Comment by zachdt** [comment]
502 in `yarn dev` or in a local build?

**Comment by zachdt** [comment]
https://github.com/vercel/next.js/issues/15981

**Comment by zachdt** [comment]
Adding a custom _error page to handle 500 errors.
