### ISSUE TITLE
TryParseAmount returning 0 for decimal inputs

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#336]
![image](https://user-images.githubusercontent.com/38409137/102531353-00854b00-4057-11eb-8824-19e29fd2fdb1.png)

Pretty sure this always returns 0 for any value less than 1 but greater than 0.

**Comment by zachdt** [comment]
Found an edge case that breaks this conditional.  `.0` is failing, `0.0` works fine.  should be able to clean this up before my PR
