### ISSUE TITLE
Order card buttons for double approval are going outside the order card

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#351]
![image](https://user-images.githubusercontent.com/38409137/102700129-9e1b7e80-41ff-11eb-8f01-1ebf79c2bb4a.png)

Interesting  css bug

**Comment by zachdt** [comment]
In swap right? I'll remove the Confirm Transaction button before approvals (like remove liquidity) while two approvals are needed.

**Comment by Alexangelj** [comment]
yes swap
