### ISSUE TITLE
Improve FAQ page and have a popup to explain some key things

### ISSUE THREAD

**Issue by Alexangelj** [primitivefinance/primitive-interface#408]
We should have an info pop up, or something to display on the homepage to explain some key characteristics of the options including:

Options must be manually exercised
Put options give you the right to buy 1 dai, so you will need the strikeprice amount of put option tokens to cover 1 underlying token.
Short options can be purchased directly for short exposure.
Anything else thats important

**Comment by zachdt** [comment]
Maybe like a second security screen.  We have the security disclosure show before/after the info popup.   I agree that we need to drill the manual exercise, put option ideosyncracies, short option token explanation, etc..., into the heads of users.
